<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <! -- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Project management app</title>
    <style>
        body{
            margin: 0;
            padding: 0;
            height: 100%;
        }
        footer{
            background-color: lightpink;
            position: absolute;
            left: 0;
            bottom: 0;
            height: 100px;
            width: 100%;
            overflow: hidden;


        }
        nav {
            background-color: lightpink;
        }

    </style>

</head>
<body>
<?php include "navbar.phtml";?>

