
<nav class="navbar navbar-expand-lg navbar-light ">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/~polaznik9/user/login">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="/~polaznik9/user/employees">Employees</a>
            <a class="nav-item nav-link" href="/~polaznik9/user/task">Tasks</a>
            <a class="nav-item nav-link" href="/~polaznik9/user/teams">Teams</a>
            <a class="nav-item nav-link" href="/~polaznik9/user/projects">Projects</a>
            <a class="nav-item nav-link" href="/~polaznik9/user/admin">Admin</a>
            <a class="nav-item nav-link" href="/~polaznik9/user/register">Registration</a>
        </div>
    </div>
</nav>
